experiments:
  feed_top_articles_query: # Points given for implicit tag weights
    variants:
      - base
      - base_with_more_articles
      - only_followed_tags
      - top_articles_since_last_pageview_3_days_max
      - top_articles_since_last_pageview_7_days_max
      - combination_only_tags_followed_and_top_max_7_days
    weights: # "base" (what we currently implement) and "no_implicit_score" are what we want the most data on.
      - 20
      - 16
      - 16
      - 16
      - 16
      - 16
    goals:
      - user_creates_comment
      - user_creates_comment_four_days_in_week
      - user_views_article_four_days_in_week
      - user_views_article_four_hours_in_day
      - user_views_article_nine_days_in_two_week
      - user_views_article_twelve_hours_in_five_days
exclude:
  bots: true

# Dashboard performance
cache: true

# For logged-in users we'll explicitely pass participant.
# If we experiment on non-logged in, we don't want to collect cookies anyway.
cookies: false
